'''
Time-Multiplexed NFA — dataloader (Nonlinear Function Approximation)

The old classification-era image-dataset loading machinery (MNIST/
FashionMNIST/CIFAR10/TinyImageNet/grating -> phase objects) has been deleted
from this file. train.py/test.py now import get_function_approx_dataloaders()
below; there is no image dataset anymore -- see target_functions.py and the
"NONLINEAR FUNCTION APPROXIMATION" section below for what replaced it.

NOTE: os/random/Path/F/np/torchvision/transforms are unused leftover imports
from that deleted code -- harmless, not cleaned up yet.
'''

import os
import random
from pathlib import Path
import torch
import torch.utils.data as data
import torch.nn.functional as F
import numpy as np
import torchvision
import torchvision.transforms as transforms

# =========================================================================== #
#  NONLINEAR FUNCTION APPROXIMATION (NFA) -- dataloader                       #
#                                                                              #
#  No images: a "sample" is just a scalar input value `a`, paired with the    #
#  Nf target function values f_k(a) (computed in closed form by              #
#  target_functions.TargetFunctionSet -- no optical simulation involved).     #
#                                                                              #
#  Training uses a FIXED POOL of config.train_a_samples random `a` values     #
#  (Monte Carlo over [a_min, a_max], reshuffled every epoch by the            #
#  DataLoader's shuffle=True -- the pool itself is drawn once, seeded by      #
#  config.seed, so it's reproducible across runs/resumes).                    #
#  Validation/test instead use a fixed, dense, EVENLY-SPACED grid             #
#  (config.val_a_grid_size / config.test_a_grid_size points), so the          #
#  reported per-function error approximates the paper's continuous RMSE      #
#  integral (Eq. 16) with low variance -- see design discussion.              #
# =========================================================================== #

from target_functions import TargetFunctionSet


class FunctionApproxDataset(data.Dataset):
    '''
    a_values  : [N] tensor of input values (already generated by the caller --
                random pool for training, dense linspace grid for val/test).
    target_fn : shared TargetFunctionSet instance -- MUST be the same object
                across train/val/test splits so they all evaluate the same
                Nf target functions.

    __getitem__ returns (a, target) where a is a scalar tensor and target is
    [Nf] -- targets are precomputed once in __init__ (cheap, closed-form,
    fully vectorized), not recomputed per __getitem__ call.
    '''

    def __init__(self, a_values, target_fn):
        super().__init__()
        self.a = a_values.to(torch.float32)
        self.targets = target_fn(self.a)   # [N, Nf], precomputed once

    def __len__(self):
        return self.a.shape[0]

    def __getitem__(self, index):
        return self.a[index], self.targets[index]


def get_function_approx_dataloaders(config):
    '''
    Returns (train_loader, val_loader, test_loader, target_fn).

    train_loader : fixed pool of config.train_a_samples random `a` values.
    val_loader / test_loader : dense, evenly-spaced grids of
                   config.val_a_grid_size / config.test_a_grid_size points.
    target_fn : the shared TargetFunctionSet (same Nf functions across all
                three splits) -- callers that need f_min/f_max (e.g. for
                sanity checks) or want to evaluate arbitrary new `a` values
                can use this directly.
    '''
    target_fn = TargetFunctionSet(config)

    gen = torch.Generator().manual_seed(int(config.seed))
    train_a = torch.rand(config.train_a_samples, generator=gen) * (config.a_max - config.a_min) + config.a_min
    val_a   = torch.linspace(config.a_min, config.a_max, config.val_a_grid_size)
    test_a  = torch.linspace(config.a_min, config.a_max, config.test_a_grid_size)

    train_ds = FunctionApproxDataset(train_a, target_fn)
    val_ds   = FunctionApproxDataset(val_a, target_fn)
    test_ds  = FunctionApproxDataset(test_a, target_fn)

    train_loader = data.DataLoader(
        train_ds,
        batch_size=config.batch_size,
        shuffle=True,
        num_workers=config.num_workers,
        pin_memory=True,
        drop_last=True,
    )
    # val/test: no drop_last -- we want the FULL dense grid covered for an
    # accurate RMSE-integral estimate and gap-free plotting, not a clean
    # batch-size multiple.
    val_loader = data.DataLoader(
        val_ds,
        batch_size=config.test_batch_size,
        shuffle=False,
        num_workers=config.num_workers,
        pin_memory=True,
    )
    test_loader = data.DataLoader(
        test_ds,
        batch_size=config.test_batch_size,
        shuffle=False,
        num_workers=config.num_workers,
        pin_memory=True,
    )

    return train_loader, val_loader, test_loader, target_fn
